name: Build and Publish Windows Desktop App

on:
  push:
    tags:
      - 'desktop-v*'

jobs:
  build:
    runs-on: windows-latest
    env:
      # Provide tokens for both electron-builder and electron (postinstall)
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Use runner temp directories as caches to avoid path issues
      ELECTRON_CACHE: ${{ runner.temp }}/electron
      ELECTRON_BUILDER_CACHE: ${{ runner.temp }}/builder
      # Avoid any auto signing discovery issues
      CSC_IDENTITY_AUTO_DISCOVERY: 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: desktop-app
        run: npm ci

      - name: Build and Publish (electron-builder)
        working-directory: desktop-app
        run: npx electron-builder --win --publish always

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: |
            desktop-app/dist/**
